import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {AppWrapper} from "@/app/AppContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html className="dark  " lang="en">
    <AppWrapper>

      <body className={inter.className +" dark:bg-[#0B132B] " }>{children}</body>
    </AppWrapper>

    </html>
  )
}
